(() => {
'use strict';
const cfg=window.WESTVIEW_CONFIG||{}, base=String(cfg.supabaseUrl||'').replace(/\/$/,''), apikey=String(cfg.supabaseKey||'');
const configured=/^https:\/\/.+\.supabase\.co$/i.test(base)&&apikey&&!apikey.startsWith('PASTE_');
const $=id=>document.getElementById(id); let session=null;
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const nice=v=>{if(!v)return'';const d=new Date(v+'T12:00:00');return Number.isNaN(d.valueOf())?v:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})};
const isFuture=v=>{if(!v)return false;const d=new Date(v+'T23:59:59');return d>new Date()};
function status(id,msg,type=''){const e=$(id);if(!e)return;e.textContent=msg;e.className='status show '+(type==='ok'?'ok':type==='bad'?'bad':'')}
function clearStatus(id){const e=$(id);if(!e)return;e.className='status';e.textContent=''}
function saveSession(s){session={...s,expires_at:Math.floor(Date.now()/1000)+(s.expires_in||3600)};sessionStorage.setItem('westviewAdminSession',JSON.stringify(session))}
function loadSession(){try{session=JSON.parse(sessionStorage.getItem('westviewAdminSession')||'null')}catch{session=null}}
async function auth(path,body){const r=await fetch(`${base}/auth/v1/${path}`,{method:'POST',headers:{apikey,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.msg||data.error_description||data.error||'Sign in failed');return data}
async function token(){if(!session)return null;if(Date.now()/1000<(session.expires_at||0)-60)return session.access_token;if(!session.refresh_token)return null;const fresh=await auth('token?grant_type=refresh_token',{refresh_token:session.refresh_token});saveSession(fresh);return session.access_token}
async function api(table,query='',opts={}){const jwt=await token();if(!jwt)throw new Error('Please sign in again.');const headers={apikey,Authorization:`Bearer ${jwt}`,'Content-Type':'application/json',...(opts.headers||{})};const r=await fetch(`${base}/rest/v1/${table}${query}`,{method:opts.method||'GET',headers,body:opts.body===undefined?undefined:JSON.stringify(opts.body)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error((data&&data.message)||`${r.status} ${r.statusText}`);return data}
async function rpc(name){return api(`rpc/${name}`,'',{method:'POST',body:{}})}
function publicFile(path){return `${base}/storage/v1/object/public/documents/${String(path).split('/').map(encodeURIComponent).join('/')}`}
async function storageUpload(path,file){const jwt=await token();const r=await fetch(`${base}/storage/v1/object/documents/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{apikey,Authorization:`Bearer ${jwt}`,'Content-Type':'application/pdf','x-upsert':'false'},body:file});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`Upload failed (${r.status})`);return d}
async function storageDelete(path){const jwt=await token();const r=await fetch(`${base}/storage/v1/object/documents`,{method:'DELETE',headers:{apikey,Authorization:`Bearer ${jwt}`,'Content-Type':'application/json'},body:JSON.stringify({prefixes:[path]})});if(!r.ok&&r.status!==404){const d=await r.json().catch(()=>({}));throw new Error(d.message||`File delete failed (${r.status})`)}}
async function verifyAdmin(){const v=await rpc('is_admin');return v===true}
function setLoggedIn(ok){$('loginPanel').style.display=ok?'none':'block';$('dashboard').classList.toggle('show',ok);$('signOut').hidden=!ok}
function itemRow(primary,secondary,type,id,href,published,editType){return `<div class="item"><div><strong>${esc(primary)}</strong><small>${esc(secondary)}</small></div><div class="item-actions">${href?`<a class="tiny" href="${esc(href)}" target="_blank" rel="noopener">Open</a>`:''}${editType?`<button class="tiny edit" data-edit="${esc(editType)}" data-id="${esc(id)}" type="button">Edit</button>`:''}${published!==undefined?`<button class="tiny ${published?'draft':'good'}" data-toggle="${esc(type)}" data-id="${esc(id)}" data-published="${published?'true':'false'}" type="button">${published?'Make draft':'Publish'}</button>`:''}<button class="tiny danger" data-delete="${esc(type)}" data-id="${esc(id)}" type="button">Delete</button></div></div>`}
const docLabels={'headteacher':'Headteacher letter','newsletter':'Newsletter','letter':'Letter home','inspection':'Ofsted / inspection','exam-timetable':'Exam timetable','exam-results':'Exam results','policy':'Policy','financial':'Financial','prospectus':'Prospectus','transport':'Transport','vacancy-pack':'Vacancy pack'};
async function loadSettings(){const rows=await api('site_settings','?select=*&id=eq.1&limit=1');const s=rows[0]||{};$('closureEnabled').checked=!!s.closure_enabled;$('closureLevel').value=s.closure_level||'weather';$('closureTitle').value=s.closure_title||'';$('closureMessage').value=s.closure_message||'';$('closureLink').value=s.closure_link||'';$('bannerEnabled').checked=s.banner_enabled!==false;$('bannerText').value=s.banner_text||'';$('bannerLink').value=s.banner_link||'';$('schoolPhone').value=s.school_phone||'';$('schoolEmail').value=s.school_email||'';$('schoolAddress').value=s.school_address||'';$('headteacherName').value=s.headteacher_name||'';window._wvSettings=s}
async function loadHouses(){const rows=await api('houses','?select=id,points');window._wvHouses=rows;rows.forEach(h=>{const e=$('house-'+h.id);if(e)e.value=h.points})}
async function loadNews(){const rows=await api('news','?select=id,title,summary,published_on,published,created_at&order=published_on.desc,created_at.desc&limit=500');window._wvNews=rows;$('newsList').innerHTML=rows.length?rows.map(n=>itemRow(n.title,`${nice(n.published_on)} · ${n.published?(isFuture(n.published_on)?'Scheduled':'Published'):'Draft'}`,'news',n.id,'',n.published)).join(''):'<div class="muted">No news posts yet.</div>';return rows}
async function loadEvents(){const rows=await api('events','?select=id,title,details,event_date,published,created_at&order=event_date.desc&limit=500');window._wvEvents=rows;$('eventList').innerHTML=rows.length?rows.map(n=>itemRow(n.title,`${nice(n.event_date)} · ${n.published?'Published':'Draft'}`,'event',n.id,'',n.published)).join(''):'<div class="muted">No events yet.</div>';return rows}
async function loadDocs(){const rows=await api('documents','?select=*&order=published_on.desc,created_at.desc&limit=500');window._wvDocs=rows;$('documentList').innerHTML=rows.length?rows.map(d=>itemRow(d.title,`${nice(d.published_on)} · ${docLabels[d.category]||d.category} · ${d.published?(isFuture(d.published_on)?'Scheduled':'Published'):'Draft'}`,'document',d.id,publicFile(d.file_path),d.published,'document')).join(''):'<div class="muted">No PDFs uploaded yet.</div>';return rows}
async function loadStaff(){const rows=await api('staff','?select=id,name,role,section,email,display_order,published&order=display_order.asc,name.asc&limit=500');window._wvStaff=rows;$('staffList').innerHTML=rows.length?rows.map(s=>itemRow(s.name,`${s.role} · ${s.section} · ${s.published?'Published':'Hidden'}`,'staff',s.id,'',s.published,'staff')).join(''):'<div class="muted">No managed staff added yet.</div>';return rows}
async function loadTransport(){const rows=await api('transport_items','?select=id,title,route_area,details,link_url,display_order,published&order=display_order.asc,title.asc&limit=500');window._wvTransport=rows;$('transportList').innerHTML=rows.length?rows.map(x=>itemRow(x.title,`${x.route_area||'General transport'} · ${x.published?'Published':'Hidden'}`,'transport',x.id,x.link_url||'',x.published,'transport')).join(''):'<div class="muted">No transport items yet.</div>';return rows}
async function loadVacancies(){const rows=await api('vacancies','?select=id,title,department,contract_type,closing_date,summary,application_url,published,created_at&order=closing_date.desc.nullslast,created_at.desc&limit=500');window._wvVacancies=rows;$('vacancyList').innerHTML=rows.length?rows.map(x=>itemRow(x.title,`${x.department||'Westview'}${x.closing_date?' · closes '+nice(x.closing_date):''} · ${x.published?'Published':'Hidden'}`,'vacancy',x.id,x.application_url||'',x.published,'vacancy')).join(''):'<div class="muted">No vacancies yet.</div>';return rows}
async function loadResults(){const rows=await api('exam_results','?select=id,academic_year,measure,result,note,display_order,published&order=academic_year.desc,display_order.asc,measure.asc&limit=500');window._wvResults=rows;$('resultList').innerHTML=rows.length?rows.map(x=>itemRow(`${x.measure} — ${x.result}`,`${x.academic_year}${x.note?' · '+x.note:''} · ${x.published?'Published':'Hidden'}`,'result',x.id,'',x.published,'result')).join(''):'<div class="muted">No exam results yet.</div>';return rows}
function updateStats(){const staff=window._wvStaff||[],news=window._wvNews||[],events=window._wvEvents||[],docs=window._wvDocs||[],transport=window._wvTransport||[],vacancies=window._wvVacancies||[],results=window._wvResults||[];const today=new Date();today.setHours(0,0,0,0);$('statStaff').textContent=staff.filter(x=>x.published).length;$('statNews').textContent=news.filter(x=>x.published&&!isFuture(x.published_on)).length;$('statEvents').textContent=events.filter(x=>x.published&&new Date(x.event_date+'T12:00:00')>=today).length;$('statDocs').textContent=docs.filter(x=>x.published&&!isFuture(x.published_on)).length;$('statTransport').textContent=transport.filter(x=>x.published).length;$('statVacancies').textContent=vacancies.filter(x=>x.published).length;$('statResults').textContent=results.filter(x=>x.published).length}
async function loadAll(){const jobs=[loadSettings(),loadHouses(),loadNews(),loadEvents(),loadDocs(),loadStaff(),loadTransport(),loadVacancies(),loadResults()];const r=await Promise.allSettled(jobs);const names=['settings','houses','news','events','documents','staff','transport','vacancies','exam results'];const failed=r.map((x,i)=>x.status==='rejected'?names[i]:null).filter(Boolean);if(failed.length)status('schoolDetailsStatus',`Could not load: ${failed.join(', ')}. Check your connection and existing Supabase setup.`,'bad');updateStats()}
function resetStaffForm(){$('staffForm').reset();$('staffId').value='';$('staffSection').value='Senior Leadership';$('staffOrder').value='100';$('staffPublished').checked=true;$('saveStaff').textContent='Add staff member';$('cancelStaffEdit').hidden=true;$('staffEditingNote').classList.remove('show');clearStatus('staffStatus')}
function resetTransportForm(){$('transportForm').reset();$('transportId').value='';$('transportOrder').value='100';$('transportPublished').checked=true;$('saveTransport').textContent='Add transport item';$('cancelTransportEdit').hidden=true;$('transportEditingNote').classList.remove('show');clearStatus('transportStatus')}
function resetVacancyForm(){$('vacancyForm').reset();$('vacancyId').value='';$('vacancyPublished').checked=true;$('saveVacancy').textContent='Add vacancy';$('cancelVacancyEdit').hidden=true;$('vacancyEditingNote').classList.remove('show');clearStatus('vacancyStatus')}
function resetResultForm(){$('resultForm').reset();$('resultId').value='';$('resultOrder').value='100';$('resultPublished').checked=true;$('saveResult').textContent='Add result';$('cancelResultEdit').hidden=true;$('resultEditingNote').classList.remove('show');clearStatus('resultStatus')}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();clearStatus('loginStatus');if(!configured){status('loginStatus','The Supabase connection is missing.','bad');return}try{status('loginStatus','Signing in…');const s=await auth('token?grant_type=password',{email:$('email').value.trim(),password:$('password').value});saveSession(s);if(!(await verifyAdmin())){sessionStorage.removeItem('westviewAdminSession');session=null;throw new Error('This account is not a Westview website administrator.')}setLoggedIn(true);await loadAll()}catch(err){status('loginStatus',err.message,'bad')}});
$('signOut').addEventListener('click',()=>{sessionStorage.removeItem('westviewAdminSession');session=null;setLoggedIn(false);$('password').value=''});
$('refreshAll').addEventListener('click',()=>loadAll().catch(e=>alert(e.message)));
$('copyAdminLink').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);$('copyAdminLink').textContent='Copied ✓';setTimeout(()=>$('copyAdminLink').textContent='Copy admin link',1400)}catch{$('copyAdminLink').textContent='Copy failed'}});
$('exportBackup').addEventListener('click',()=>{const payload={exported_at:new Date().toISOString(),site_settings:window._wvSettings||{},houses:window._wvHouses||[],staff:window._wvStaff||[],news:window._wvNews||[],events:window._wvEvents||[],documents:window._wvDocs||[],transport:window._wvTransport||[],vacancies:window._wvVacancies||[],exam_results:window._wvResults||[]};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`westview-data-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
$('saveClosure').addEventListener('click',async()=>{try{status('closureStatus','Saving…');await api('site_settings','?id=eq.1',{method:'PATCH',headers:{Prefer:'return=minimal'},body:{closure_enabled:$('closureEnabled').checked,closure_level:$('closureLevel').value,closure_title:$('closureTitle').value.trim(),closure_message:$('closureMessage').value.trim(),closure_link:$('closureLink').value.trim()||null,closure_updated:new Date().toISOString()}});status('closureStatus',$('closureEnabled').checked?'Live notice saved and switched ON.':'Notice saved and remains OFF.','ok')}catch(e){status('closureStatus',e.message,'bad')}});
$('disableClosure').addEventListener('click',async()=>{try{if(!confirm('Switch the homepage closure / urgent notice off now?'))return;await api('site_settings','?id=eq.1',{method:'PATCH',headers:{Prefer:'return=minimal'},body:{closure_enabled:false,closure_updated:new Date().toISOString()}});$('closureEnabled').checked=false;status('closureStatus','Homepage closure / urgent notice is OFF.','ok')}catch(e){status('closureStatus',e.message,'bad')}});
$('saveBanner').addEventListener('click',async()=>{try{status('bannerStatus','Saving…');await api('site_settings','?id=eq.1',{method:'PATCH',headers:{Prefer:'return=minimal'},body:{banner_enabled:$('bannerEnabled').checked,banner_text:$('bannerText').value.trim(),banner_link:$('bannerLink').value.trim()||'letters.html'}});status('bannerStatus','Homepage update strip saved.','ok')}catch(e){status('bannerStatus',e.message,'bad')}});
$('saveSchoolDetails').addEventListener('click',async()=>{try{status('schoolDetailsStatus','Saving…');await api('site_settings','?id=eq.1',{method:'PATCH',headers:{Prefer:'return=minimal'},body:{school_phone:$('schoolPhone').value.trim(),school_email:$('schoolEmail').value.trim(),school_address:$('schoolAddress').value.trim(),headteacher_name:$('headteacherName').value.trim()}});status('schoolDetailsStatus','School details updated across the website.','ok');await loadSettings()}catch(e){status('schoolDetailsStatus',e.message,'bad')}});
$('saveHouses').addEventListener('click',async()=>{try{status('houseStatus','Updating…');for(const id of ['brunel','nightingale','turing','seacole'])await api('houses',`?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{points:Number($('house-'+id).value||0),updated_at:new Date().toISOString()}});status('houseStatus','House points updated.','ok');await loadHouses()}catch(e){status('houseStatus',e.message,'bad')}});
$('newsForm').addEventListener('submit',async e=>{e.preventDefault();try{status('newsStatus','Posting…');await api('news','',{method:'POST',headers:{Prefer:'return=minimal'},body:{title:$('newsTitle').value.trim(),summary:$('newsSummary').value.trim(),published_on:$('newsDate').value,published:$('newsPublished').checked}});e.target.reset();$('newsPublished').checked=true;status('newsStatus','News post added.','ok');await loadNews();updateStats()}catch(err){status('newsStatus',err.message,'bad')}});
$('eventForm').addEventListener('submit',async e=>{e.preventDefault();try{status('eventStatus','Adding…');await api('events','',{method:'POST',headers:{Prefer:'return=minimal'},body:{title:$('eventTitle').value.trim(),details:$('eventDetails').value.trim(),event_date:$('eventDate').value,published:$('eventPublished').checked}});e.target.reset();$('eventPublished').checked=true;status('eventStatus','Event added.','ok');await loadEvents();updateStats()}catch(err){status('eventStatus',err.message,'bad')}});
$('staffForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('staffId').value;const body={name:$('staffName').value.trim(),role:$('staffRole').value.trim(),section:$('staffSection').value.trim()||'Key Staff',email:$('staffEmail').value.trim()||null,display_order:Number($('staffOrder').value||100),published:$('staffPublished').checked,updated_at:new Date().toISOString()};try{status('staffStatus',id?'Saving staff changes…':'Adding staff member…');if(id)await api('staff',`?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body});else await api('staff','',{method:'POST',headers:{Prefer:'return=minimal'},body});status('staffStatus',id?'Staff member updated.':'Staff member added.','ok');resetStaffForm();await loadStaff();updateStats()}catch(err){status('staffStatus',err.message,'bad')}});
$('cancelStaffEdit').addEventListener('click',resetStaffForm);
$('transportForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('transportId').value;const body={title:$('transportTitle').value.trim(),route_area:$('transportArea').value.trim()||null,details:$('transportDetails').value.trim(),link_url:$('transportLink').value.trim()||null,display_order:Number($('transportOrder').value||100),published:$('transportPublished').checked,updated_at:new Date().toISOString()};try{status('transportStatus',id?'Saving changes…':'Adding transport item…');if(id)await api('transport_items',`?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body});else await api('transport_items','',{method:'POST',headers:{Prefer:'return=minimal'},body});status('transportStatus','Transport information saved.','ok');resetTransportForm();await loadTransport();updateStats()}catch(err){status('transportStatus',err.message,'bad')}});
$('cancelTransportEdit').addEventListener('click',resetTransportForm);
$('vacancyForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('vacancyId').value;const body={title:$('vacancyTitle').value.trim(),department:$('vacancyDepartment').value.trim()||null,contract_type:$('vacancyContract').value.trim()||null,closing_date:$('vacancyClosing').value||null,summary:$('vacancySummary').value.trim()||'',application_url:$('vacancyApplication').value.trim()||null,published:$('vacancyPublished').checked,updated_at:new Date().toISOString()};try{status('vacancyStatus',id?'Saving vacancy…':'Adding vacancy…');if(id)await api('vacancies',`?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body});else await api('vacancies','',{method:'POST',headers:{Prefer:'return=minimal'},body});status('vacancyStatus','Vacancy saved.','ok');resetVacancyForm();await loadVacancies();updateStats()}catch(err){status('vacancyStatus',err.message,'bad')}});
$('cancelVacancyEdit').addEventListener('click',resetVacancyForm);
$('resultForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('resultId').value;const body={academic_year:$('resultYear').value.trim(),measure:$('resultMeasure').value.trim(),result:$('resultValue').value.trim(),note:$('resultNote').value.trim()||null,display_order:Number($('resultOrder').value||100),published:$('resultPublished').checked,updated_at:new Date().toISOString()};try{status('resultStatus',id?'Saving result…':'Adding result…');if(id)await api('exam_results',`?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body});else await api('exam_results','',{method:'POST',headers:{Prefer:'return=minimal'},body});status('resultStatus','Exam result saved.','ok');resetResultForm();await loadResults();updateStats()}catch(err){status('resultStatus',err.message,'bad')}});
$('cancelResultEdit').addEventListener('click',resetResultForm);

function resetDocumentForm(){
 $('documentForm').reset();$('docEditId').value='';$('docFile').required=true;$('docFile').disabled=false;
 $('docPublished').checked=true;$('saveDoc').textContent='Upload PDF';$('cancelDocEdit').hidden=true;
 $('docEditNote').hidden=true;$('docBody').dispatchEvent(new Event('input'));
}
$('cancelDocEdit').addEventListener('click',resetDocumentForm);
$('documentForm').addEventListener('submit',async e=>{
 e.preventDefault();const id=$('docEditId').value,file=$('docFile').files[0],text=$('docBody').value.trim();
 const existing=(window._wvDocs||[]).find(d=>String(d.id)===id);
 const body={title:$('docTitle').value.trim(),summary:$('docSummary').value.trim()||'',category:$('docCategory').value,published_on:$('docDate').value,published:$('docPublished').checked};
 if(text||existing&&Object.prototype.hasOwnProperty.call(existing,'letter_body'))body.letter_body=text;
 let uploaded=false,path='';
 const saveButton=$('saveDoc');saveButton.disabled=true;
 try{
  if(id){status('docStatus','Saving document…');await api('documents','?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=minimal'},body});}
  else{
   if(!file)throw new Error('Please choose a PDF file.');
   if(!(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')))throw new Error('Please choose a PDF file.');
   if(file.size>10*1024*1024)throw new Error('PDF must be 10 MB or smaller.');
   status('docStatus','Uploading PDF…');
   const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-');
   path=body.category+'/'+body.published_on+'-'+Date.now()+'-'+safe;
   await storageUpload(path,file);uploaded=true;
   await api('documents','',{method:'POST',headers:{Prefer:'return=minimal'},body:{...body,file_path:path,file_name:file.name}});uploaded=false;
  }
  resetDocumentForm();status('docStatus',id?'Document text and details saved. Your PDF is unchanged.':'PDF uploaded successfully.','ok');
  await loadDocs();updateStats();
 }catch(err){
  if(uploaded)try{await storageDelete(path)}catch{}
  status('docStatus',/letter_body/.test(err.message)?'Run WESTVIEW-LETTER-UPGRADE.sql in your existing Supabase project once to enable letter text. Your typed text is still here.':err.message,'bad');
 }finally{saveButton.disabled=false}
});
document.querySelectorAll('[data-doc-cat]').forEach(b=>b.addEventListener('click',()=>{$('docCategory').value=b.dataset.docCat;$('docTitle').focus()}));
document.addEventListener('click',async e=>{
  const edit=e.target.closest('[data-edit]');
  if(edit){const type=edit.dataset.edit,id=edit.dataset.id;
    if(type==='document'){
      const d=(window._wvDocs||[]).find(x=>String(x.id)===String(id));if(!d)return;
      $('docEditId').value=d.id;$('docTitle').value=d.title||'';$('docSummary').value=d.summary||'';
      $('docCategory').value=d.category;$('docDate').value=d.published_on;$('docPublished').checked=!!d.published;
      $('docBody').value=d.letter_body||'';$('docBody').dispatchEvent(new Event('input'));
      $('docFile').required=false;$('docFile').disabled=true;$('saveDoc').textContent='Save document changes';
      $('cancelDocEdit').hidden=false;$('docEditNote').hidden=false;
      $('documentForm').scrollIntoView({behavior:'smooth',block:'start'});$('docTitle').focus();return;
    }
    if(type==='staff'){const s=(window._wvStaff||[]).find(x=>String(x.id)===String(id));if(!s)return;$('staffId').value=s.id;$('staffName').value=s.name||'';$('staffRole').value=s.role||'';$('staffSection').value=s.section||'Key Staff';$('staffEmail').value=s.email||'';$('staffOrder').value=s.display_order??100;$('staffPublished').checked=!!s.published;$('saveStaff').textContent='Save staff changes';$('cancelStaffEdit').hidden=false;$('staffEditingNote').classList.add('show');$('staffForm').scrollIntoView({behavior:'smooth',block:'start'});return}
    if(type==='transport'){const x=(window._wvTransport||[]).find(x=>String(x.id)===String(id));if(!x)return;$('transportId').value=x.id;$('transportTitle').value=x.title||'';$('transportArea').value=x.route_area||'';$('transportDetails').value=x.details||'';$('transportLink').value=x.link_url||'';$('transportOrder').value=x.display_order??100;$('transportPublished').checked=!!x.published;$('saveTransport').textContent='Save transport changes';$('cancelTransportEdit').hidden=false;$('transportEditingNote').classList.add('show');$('transportForm').scrollIntoView({behavior:'smooth',block:'start'});return}
    if(type==='vacancy'){const x=(window._wvVacancies||[]).find(x=>String(x.id)===String(id));if(!x)return;$('vacancyId').value=x.id;$('vacancyTitle').value=x.title||'';$('vacancyDepartment').value=x.department||'';$('vacancyContract').value=x.contract_type||'';$('vacancyClosing').value=x.closing_date||'';$('vacancySummary').value=x.summary||'';$('vacancyApplication').value=x.application_url||'';$('vacancyPublished').checked=!!x.published;$('saveVacancy').textContent='Save vacancy changes';$('cancelVacancyEdit').hidden=false;$('vacancyEditingNote').classList.add('show');$('vacancyForm').scrollIntoView({behavior:'smooth',block:'start'});return}
    if(type==='result'){const x=(window._wvResults||[]).find(x=>String(x.id)===String(id));if(!x)return;$('resultId').value=x.id;$('resultYear').value=x.academic_year||'';$('resultMeasure').value=x.measure||'';$('resultValue').value=x.result||'';$('resultNote').value=x.note||'';$('resultOrder').value=x.display_order??100;$('resultPublished').checked=!!x.published;$('saveResult').textContent='Save result changes';$('cancelResultEdit').hidden=false;$('resultEditingNote').classList.add('show');$('resultForm').scrollIntoView({behavior:'smooth',block:'start'});return}
  }
  const toggle=e.target.closest('[data-toggle]');
  if(toggle){const type=toggle.dataset.toggle,id=toggle.dataset.id,next=toggle.dataset.published!=='true';toggle.disabled=true;try{const tables={event:'events',document:'documents',staff:'staff',news:'news',transport:'transport_items',vacancy:'vacancies',result:'exam_results'};await api(tables[type],`?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{published:next,updated_at:new Date().toISOString()}}).catch(async err=>{if(/updated_at/.test(err.message))await api(tables[type],`?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{published:next}});else throw err});const loaders={event:loadEvents,document:loadDocs,staff:loadStaff,news:loadNews,transport:loadTransport,vacancy:loadVacancies,result:loadResults};await loaders[type]();updateStats()}catch(err){alert(err.message)}finally{toggle.disabled=false}return}
  const b=e.target.closest('[data-delete]');if(!b)return;const type=b.dataset.delete,id=b.dataset.id;if(!confirm('Delete this item?'))return;b.disabled=true;try{const tables={news:'news',event:'events',staff:'staff',transport:'transport_items',vacancy:'vacancies',result:'exam_results'};const loaders={news:loadNews,event:loadEvents,staff:loadStaff,transport:loadTransport,vacancy:loadVacancies,result:loadResults};if(type==='document'){const d=(window._wvDocs||[]).find(x=>String(x.id)===String(id));if(d?.file_path)await storageDelete(d.file_path);await api('documents',`?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await loadDocs()}else{await api(tables[type],`?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});await loaders[type]();if(type==='staff')resetStaffForm();if(type==='transport')resetTransportForm();if(type==='vacancy')resetVacancyForm();if(type==='result')resetResultForm()}updateStats()}catch(err){alert(err.message)}finally{b.disabled=false}
});
if(!configured)$('configWarning').hidden=false;
loadSession();(async()=>{if(session&&configured){try{if(await verifyAdmin()){setLoggedIn(true);await loadAll();return}}catch{}sessionStorage.removeItem('westviewAdminSession');session=null}setLoggedIn(false)})();
})();
