(() => {
'use strict';
const cfg=window.WESTVIEW_CONFIG||{};const url=String(cfg.supabaseUrl||'').replace(/\/$/,'');const key=String(cfg.supabaseKey||'');const configured=/^https:\/\/.+\.supabase\.co$/i.test(url)&&key&&!key.startsWith('PASTE_');
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function letterBlock(value){if(!value||!String(value).trim())return '';return '<details class="letter-text"><summary>Read letter text</summary><div class="letter-body">'+String(value).trim().split(/\n[ \t]*\n+/).map(p=>'<p>'+esc(p)+'</p>').join('')+'</div></details>'}
const niceDate=v=>{if(!v)return'';const d=new Date(v+(String(v).length===10?'T12:00:00':''));return Number.isNaN(d.valueOf())?String(v):d.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})};
const eventBadge=v=>{const d=new Date(v+'T12:00:00');return Number.isNaN(d.valueOf())?'DATE':d.toLocaleDateString('en-GB',{month:'short',day:'2-digit'}).toUpperCase()};
function publicFile(path,filename=''){const q=filename?`?download=${encodeURIComponent(filename)}`:'?download=';return `${url}/storage/v1/object/public/documents/${String(path).split('/').map(encodeURIComponent).join('/')}${q}`}
async function get(table,query='',fallback=false){if(table==='documents'&&!fallback)query=query.replace('&published=','&published=').replace('file_name&','file_name,letter_body&');if(!configured)throw new Error('Westview live data is not configured.');const r=await fetch(`${url}/rest/v1/${table}${query}`,{headers:{apikey:key,'Accept':'application/json'}});if(!r.ok){if(table==='documents'&&!fallback&&r.status===400)return get(table,query.replace(',letter_body',''),true);throw new Error(`${table}: ${r.status}`);}return r.json()}
const docLabels={'headteacher':'Headteacher letter','newsletter':'Newsletter','letter':'Letter home','inspection':'Ofsted / inspection report','exam-timetable':'Exam timetable','exam-results':'Exam results','policy':'School policy','financial':'Financial document','prospectus':'Prospectus','transport':'Transport document','vacancy-pack':'Vacancy / application pack'};
function showClosure(s){if(!s||!s.closure_enabled||!document.body.matches('[data-westview-home]'))return;const version=s.closure_updated||s.closure_title||'current';const dismissKey='westview-alert:'+version;if(sessionStorage.getItem(dismissKey)==='1')return;const level=['weather','urgent','info'].includes(s.closure_level)?s.closure_level:'weather';const icon=level==='info'?'i':'!';const wrap=document.createElement('div');wrap.className='wv-alert-backdrop';wrap.setAttribute('role','dialog');wrap.setAttribute('aria-modal','true');wrap.setAttribute('aria-label',s.closure_title||'School notice');const link=s.closure_link?`<a class="wv-alert-btn secondary" href="${esc(s.closure_link)}">More information</a>`:'';wrap.innerHTML=`<div class="wv-alert ${level}"><div class="wv-alert-head"><div class="wv-alert-icon">${icon}</div><div><p>Important Westview notice</p><h2>${esc(s.closure_title||'School update')}</h2></div><button class="wv-alert-close" type="button" aria-label="Close notice">×</button></div><div class="wv-alert-body"><p>${esc(s.closure_message||'Please check the latest school information before travelling.')}</p><div class="wv-alert-actions">${link}<button class="wv-alert-btn" type="button" data-close>Close</button></div></div></div>`;const close=()=>{sessionStorage.setItem(dismissKey,'1');wrap.remove()};wrap.querySelector('.wv-alert-close').addEventListener('click',close);wrap.querySelector('[data-close]').addEventListener('click',close);wrap.addEventListener('click',e=>{if(e.target===wrap)close()});document.addEventListener('keydown',function once(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',once)}});document.body.appendChild(wrap);setTimeout(()=>wrap.querySelector('.wv-alert-close')?.focus(),0)}
function applyBanner(s){const n=document.querySelector('.notice');if(!n||!s)return;if(s.banner_enabled===false){n.style.display='none';return}n.style.display='';if(s.banner_text){const p=n.querySelector('p');if(p)p.textContent=s.banner_text;const a=n.querySelector('a');if(a&&s.banner_link)a.href=s.banner_link}}
function applySchoolDetails(s){if(!s)return;document.querySelectorAll('[data-westview-school-address]').forEach(e=>{if(s.school_address)e.innerHTML=String(s.school_address).split(/\r?\n/).map(esc).join('<br>')});document.querySelectorAll('[data-westview-school-phone]').forEach(e=>{if(s.school_phone){e.textContent=s.school_phone;if(e.tagName==='A')e.href='tel:'+String(s.school_phone).replace(/[^+\d]/g,'')}});document.querySelectorAll('[data-westview-school-email]').forEach(e=>{if(s.school_email){e.textContent=s.school_email;if(e.tagName==='A')e.href='mailto:'+s.school_email}});document.querySelectorAll('[data-westview-headteacher]').forEach(e=>{if(s.headteacher_name)e.textContent=s.headteacher_name})}
async function loadSettings(){const rows=await get('site_settings','?select=*&id=eq.1&limit=1');const s=rows[0];showClosure(s);applyBanner(s);applySchoolDetails(s)}
async function loadHouses(){if(!document.querySelector('[data-house-id]'))return;const rows=await get('houses','?select=id,name,points');rows.forEach(h=>document.querySelectorAll(`[data-house-id="${CSS.escape(h.id)}"]`).forEach(card=>{const score=card.querySelector('.score');if(score)score.innerHTML=`${Number(h.points||0).toLocaleString('en-GB')} <small>points</small>`}))}
async function loadNews(){const target=document.getElementById('westviewNews');if(!target)return;const rows=await get('news','?select=id,title,summary,published_on&published=eq.true&order=published_on.desc,created_at.desc&limit=10');const today=new Date();today.setHours(23,59,59,999);const visible=rows.filter(n=>new Date(n.published_on+'T12:00:00')<=today).slice(0,2);if(!visible.length){target.innerHTML='<p class="wv-empty">There are no school news updates to show.</p>';return}target.innerHTML=visible.map((n,i)=>`<article class="news-card"${i?' style="margin-top:12px"':''}><time>${esc(niceDate(n.published_on))}</time><h3>${esc(n.title)}</h3><p>${esc(n.summary||'')}</p></article>`).join('')}
async function loadEvents(){const target=document.getElementById('westviewEvents');if(!target)return;const rows=await get('events','?select=id,title,details,event_date&published=eq.true&order=event_date.asc&limit=25');const today=new Date();today.setHours(0,0,0,0);const upcoming=rows.filter(x=>new Date(x.event_date+'T12:00:00')>=today).slice(0,3);if(!upcoming.length){target.innerHTML='<p class="wv-empty">No upcoming events have been published. Please see the calendar for term dates.</p>';return}target.innerHTML=upcoming.map(e=>`<article class="event-card"><span class="event-date">${esc(eventBadge(e.event_date))}</span><h3>${esc(e.title)}</h3><p>${esc(e.details||niceDate(e.event_date))}</p></article>`).join('')}
async function loadCalendarEvents(){const target=document.getElementById('westviewCalendarEvents');if(!target)return;const rows=await get('events','?select=id,title,details,event_date&published=eq.true&order=event_date.asc&limit=100');if(!rows.length){target.innerHTML='<div class="wv-empty">No additional events have been published yet.</div>';return}target.innerHTML=rows.map(e=>`<div class="wv-doc"><div class="wv-pdf">DATE</div><div><h3>${esc(e.title)}</h3><p>${esc(niceDate(e.event_date))}${e.details?' · '+esc(e.details):''}</p></div></div>`).join('')}
async function loadDocuments(){const targets=[...document.querySelectorAll('[data-westview-documents]')];if(!targets.length)return;const all=await get('documents','?select=id,title,summary,category,published_on,file_path,file_name&published=eq.true&order=published_on.desc,created_at.desc&limit=250');const today=new Date();today.setHours(23,59,59,999);const visibleAll=all.filter(d=>new Date(d.published_on+'T12:00:00')<=today);for(const t of targets){const cats=t.dataset.westviewDocuments.split(',').map(x=>x.trim()).filter(Boolean);const rows=visibleAll.filter(d=>cats.includes(d.category));if(!rows.length){t.innerHTML='<div class="wv-empty">No published documents yet.</div>';continue}t.innerHTML=rows.map(d=>`<article class="wv-doc"><div class="wv-pdf">PDF</div><div><h3>${esc(d.title)}</h3><p>${esc(niceDate(d.published_on))} · ${esc(docLabels[d.category]||d.category)}${d.summary?' · '+esc(d.summary):''}</p></div><a href="${publicFile(d.file_path,d.file_name)}" target="_blank" rel="noopener" download>Download PDF</a>${letterBlock(d.letter_body)}</article>`).join('')}}
async function loadStaff(){const target=document.getElementById('westviewStaffDirectory');if(!target)return;const rows=await get('staff','?select=id,name,role,section,email,display_order,published&published=eq.true&order=display_order.asc,name.asc&limit=250');if(!rows.length)return;const groups=new Map();rows.forEach(s=>{const section=(s.section||'Key staff').trim()||'Key staff';if(!groups.has(section))groups.set(section,[]);groups.get(section).push(s)});target.innerHTML=[...groups.entries()].map(([section,people])=>`<section class="wv-staff-section"><h2>${esc(section)}</h2><table class="table"><tr><th>Role</th><th>Name</th></tr>${people.map(p=>`<tr><td>${esc(p.role)}</td><td><strong>${esc(p.name)}</strong>${p.email?`<div class="wv-staff-email"><a href="mailto:${esc(p.email)}">${esc(p.email)}</a></div>`:''}</td></tr>`).join('')}</table></section>`).join('')}
async function loadTransport(){const target=document.getElementById('westviewTransport');if(!target)return;const rows=await get('transport_items','?select=id,title,route_area,details,link_url,display_order&published=eq.true&order=display_order.asc,title.asc&limit=100');if(!rows.length){target.innerHTML='<div class="wv-empty">No transport information has been published yet.</div>';return}target.innerHTML=`<div class="wv-managed-grid">${rows.map(x=>`<article class="wv-managed-card"><div class="wv-meta">${esc(x.route_area||'School transport')}</div><h3>${esc(x.title)}</h3><p>${esc(x.details||'')}</p>${x.link_url?`<a class="wv-action" href="${esc(x.link_url)}" target="_blank" rel="noopener">More information</a>`:''}</article>`).join('')}</div>`}
async function loadVacancies(){const target=document.getElementById('westviewVacancies');if(!target)return;const rows=await get('vacancies','?select=id,title,department,contract_type,closing_date,summary,application_url&published=eq.true&order=closing_date.asc.nullslast,created_at.desc&limit=100');if(!rows.length){target.innerHTML='<div class="wv-empty">There are currently no published vacancies.</div>';return}target.innerHTML=`<div class="wv-managed-grid">${rows.map(x=>`<article class="wv-managed-card"><div class="wv-meta">${esc([x.department,x.contract_type].filter(Boolean).join(' · ')||'Westview vacancy')}</div><h3>${esc(x.title)}</h3><p>${esc(x.summary||'')}</p>${x.closing_date?`<p><strong>Closing date:</strong> ${esc(niceDate(x.closing_date))}</p>`:''}${x.application_url?`<a class="wv-action" href="${esc(x.application_url)}" target="_blank" rel="noopener">Apply / application information</a>`:''}</article>`).join('')}</div>`}
async function loadExamResults(){const target=document.getElementById('westviewExamResults');if(!target)return;const rows=await get('exam_results','?select=id,academic_year,measure,result,note,display_order&published=eq.true&order=academic_year.desc,display_order.asc,measure.asc&limit=250');if(!rows.length){target.innerHTML='<div class="wv-empty">No examination results have been published yet.</div>';return}target.innerHTML=`<table class="wv-result-table"><thead><tr><th>Academic year</th><th>Measure</th><th>Result</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.academic_year)}</td><td>${esc(x.measure)}${x.note?`<span class="wv-result-note">${esc(x.note)}</span>`:''}</td><td><strong>${esc(x.result)}</strong></td></tr>`).join('')}</tbody></table>`}

async function loadHomepageLatestDocs(){const target=document.getElementById('westviewLatestDocs');const heroTitle=document.getElementById('wvLatestDocTitle');const heroMeta=document.getElementById('wvLatestDocMeta');if(!target&&!heroTitle)return;const rows=await get('documents','?select=id,title,summary,category,published_on,file_path,file_name&published=eq.true&order=published_on.desc,created_at.desc&limit=30');const today=new Date();today.setHours(23,59,59,999);const visible=rows.filter(d=>new Date(d.published_on+'T12:00:00')<=today).slice(0,3);if(heroTitle&&visible[0]){heroTitle.textContent=visible[0].title;heroMeta.textContent=`${niceDate(visible[0].published_on)} · ${docLabels[visible[0].category]||visible[0].category}`}if(target){target.innerHTML=visible.length?visible.map(d=>`<article class="wv-latest-doc"><small>${esc(docLabels[d.category]||d.category)}</small><strong>${esc(d.title)}</strong><span>${esc(d.summary||niceDate(d.published_on))}</span><a href="${publicFile(d.file_path,d.file_name)}" target="_blank" rel="noopener">Open PDF →</a>${letterBlock(d.letter_body)}</article>`).join(''):'<article class="wv-latest-doc"><small>Document hub</small><strong>No public documents yet</strong><span>Published PDFs will appear here automatically.</span><a href="documents.html">Open Document Hub →</a></article>'}}
async function loadNewsArchive(){const target=document.getElementById('westviewNewsArchive');if(!target)return;const rows=await get('news','?select=id,title,summary,published_on&published=eq.true&order=published_on.desc,created_at.desc&limit=250');const today=new Date();today.setHours(23,59,59,999);const visible=rows.filter(n=>new Date(n.published_on+'T12:00:00')<=today);target.innerHTML=visible.length?visible.map(n=>`<article class="wv-archive-card"><time>${esc(niceDate(n.published_on))}</time><h3>${esc(n.title)}</h3><p>${esc(n.summary||'')}</p></article>`).join(''):'<div class="wv-empty">No school news has been published yet.</div>'}
async function loadDocumentHub(){const target=document.getElementById('westviewDocumentHub');if(!target)return;const rows=await get('documents','?select=id,title,summary,category,published_on,file_path,file_name&published=eq.true&order=published_on.desc,created_at.desc&limit=500');const today=new Date();today.setHours(23,59,59,999);const visible=rows.filter(d=>new Date(d.published_on+'T12:00:00')<=today);let filter='all',query='';const render=()=>{const out=visible.filter(d=>(filter==='all'||d.category===filter)&&(!query||`${d.title} ${d.summary||''} ${docLabels[d.category]||d.category}`.toLowerCase().includes(query)));target.innerHTML=out.length?out.map(d=>`<article class="wv-doc" data-category="${esc(d.category)}"><div class="wv-pdf">PDF</div><div><h3>${esc(d.title)}</h3><p>${esc(niceDate(d.published_on))} · ${esc(docLabels[d.category]||d.category)}${d.summary?' · '+esc(d.summary):''}</p></div><a href="${publicFile(d.file_path,d.file_name)}" target="_blank" rel="noopener" download>Download PDF</a>${letterBlock(d.letter_body)}</article>`).join(''):'<div class="wv-empty">No documents match that filter.</div>'};document.querySelectorAll('#wvDocFilters button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#wvDocFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()}));const search=document.getElementById('wvDocSearch');search?.addEventListener('input',()=>{query=search.value.trim().toLowerCase();render()});render()}
async function loadNextEventSummary(){const el=document.getElementById('wvNextKeyDate');const status=document.getElementById('wvStatusTerm');if(!el&&!status)return;const rows=await get('events','?select=title,event_date&published=eq.true&order=event_date.asc&limit=50');const now=new Date();now.setHours(0,0,0,0);const next=rows.find(x=>new Date(x.event_date+'T12:00:00')>=now);if(next){if(el){el.textContent=`${eventBadge(next.event_date)} · ${next.title}`;el.dataset.liveFilled='1'}if(status)status.textContent=`${niceDate(next.event_date)} · ${next.title}`}}


const jobs=[[loadSettings,[]],[loadHouses,[]],[loadNews,['westviewNews']],[loadEvents,['westviewEvents']],[loadCalendarEvents,['westviewCalendarEvents']],[loadDocuments,[]],[loadStaff,[]],[loadTransport,['westviewTransport']],[loadVacancies,['westviewVacancies']],[loadExamResults,['westviewExamResults']],[loadHomepageLatestDocs,['westviewLatestDocs']],[loadNewsArchive,['westviewNewsArchive']],[loadDocumentHub,['westviewDocumentHub']],[loadNextEventSummary,[]]];
if(!configured){document.querySelectorAll('.load-note').forEach(n=>n.textContent='School updates are temporarily unavailable. Please try again later.');return}
Promise.allSettled(jobs.map(async([fn,ids])=>{try{await fn()}catch(error){ids.forEach(id=>{const target=document.getElementById(id);if(target)target.innerHTML='<p class="wv-empty" role="status">We could not load this information. Please refresh the page to try again.</p>'});if(fn===loadDocuments)document.querySelectorAll('[data-westview-documents]').forEach(t=>t.innerHTML='<p class="wv-empty">Documents are temporarily unavailable. Please refresh to try again.</p>');}}));

})();
